### ISSUE TITLE
Crashes on Xiaomi devices

### ISSUE THREAD

**Issue by 2mt-hillen** [iamolegga/react-native-launch-arguments#8] opened 2021-03-17 10:22 UTC
Hello this library is awesome for testing, but since we are using this library we get some crashes on Devices with MIUI (Xiaomi, Redmi, Poco, etc.)

`com.facebook.react.common.JavascriptException: Error: Exception in HostObject::get(propName:LaunchArguments): java.lang.IllegalArgumentException: Could not convert class android.os.UserHandle`

**Comment by iamolegga** [comment] 2021-03-17 15:15
Hi, thanks for reporting, can it be related to testing framework: Detox or Appium?

Btw, it would be helpful if there would be more details or maybe small example repo with steps to reproduce the bug

**Comment by 2mt-hillen** [comment] 2021-03-17 15:16
We are using Detox

**Comment by 2mt-hillen** [comment] 2021-03-17 15:16
the small example could take a moment

**Comment by iamolegga** [comment] 2021-03-18 08:33
I can suggest uninstall this package, and keep sending launch args with Detox, so we could know if this is Detox's problem or this package's

**Comment by 2mt-hillen** [comment] 2021-03-18 10:15
> 
> 
> I can suggest uninstall this package, and keep sending launch args with Detox, so we could know if this is Detox's problem or this package's

that would probably our next step,
sorry, the example repo could take longer as expected, we got alot of other stuff to do right now :/

**Comment by 2mt-hillen** [comment] 2021-03-21 19:06
So we removed your package, while keeping detox, and the problem isn't showing now.

**Comment by iamolegga** [comment] 2021-03-22 07:58
Can you please try with v1 just to check if problem appeared with new code to support of appium?

**Comment by danecando** [comment] 2021-03-30 13:55
> Can you please try with v1 just to check if problem appeared with new code to support of appium?

@iamolegga I can confirm that rolling back to v1 cleared this up for a user affected by this issue

**Comment by iamolegga** [comment] 2021-03-30 15:03
Thanks @danecando ! cc @bgalamb , can you please find the reason [in this commit](https://github.com/iamolegga/react-native-launch-arguments/commit/2000bebce521fc91135f1875ee05e4689e9c664b)

**Comment by bgalamb** [comment] 2021-03-31 08:11
Hi @danecando . The fundamental thing in the prev commit was to pass ALL launch arguments to the React App, not only the one with name 'LaunchArgs'

I think the problem may come from a cast error in your? code :(. The parameter `propName:LaunchArguments` cannot be cast to `android.os.UserHandle`. 

You can experiment and try to find the reason by modifying directly the java source:
`<your_git_repo>/react-native/mobile/node_modules/react-native-launch-arguments/android/src/main/java/com/reactnativelauncharguments.LaunchArgumentsModule.java`

**Comment by iamolegga** [comment] 2021-04-01 15:25
So what should we do now? Should we add extra docs on some limitations or change code to make it not throwing error or drop appium support?

**Comment by bgalamb** [comment] 2021-04-01 17:52
Pls don't drop appium support, many are using it and there are 400+ weekly downloads.

I think this issue was coding error on consumer side. (my code does not throw error). Maybe we could add some content to the readme.md. A kind of migration from 1.0 to 2.0. Maybe @danecando can suggest what to do to make it clearer.

**Comment by danecando** [comment] 2021-04-02 16:56
Just a heads up I'm not the author or a contributor to this package and I don't have the time to try and solve the problem

**Comment by bgalamb** [comment] 2021-04-07 19:07
Ok. To avoid such cases Im going to add migration guide.

**Comment by stigi** [comment] 2021-05-31 07:22
> Ok. To avoid such cases Im going to add migration guide.

@bgalamb what kind of migration are you referring to? Following the discussion in this issue I could not see another solution besides downgrading the lib to 1.0.2, and hope that this will get the crashes out of the way (I don't have a Xiaomi device to verify 😞)

**Comment by bgalamb** [comment] 2021-06-03 19:35
I didn't write it sorry. I realised that this error is probably coming from Android implementation differences on Xiaomi. But I don't have Xiaomi neither :( so I could not debug.

**Comment by iamolegga** [comment] 2021-06-04 12:22
@bgalamb unfortunately I think the best solutioin here is drop support of appium in new major release. This lib was built with support of **detox** in mind, I didn't have any experience with Appium, and I can not solve this bug on my own. So I prefer having library with support of one frameworks but without bugs to library that supports two frameworks but has bugs.

So let's give this bug a couple of weeks, maybe someone could solve this. If not feel free to fork this lib and use it in current state if you need support of Appium, it has MIT license, so should not be any problems with transition. Thanks!

**Comment by bgalamb** [comment] 2021-06-04 14:52
Hi @iamolegga . I think this issue only affects Xiaomi devices, so I would rather state this as a limitation instead of dropping the whole feature. Also consider that the library is over 2000weekly downloads and I believe it's because of the possibility to pass more than one argument (not only by appium, but by ADB too)
Maybe @stigi or @danecando could debug the 5 lines of code, to find the root cause..
```
 Bundle bundleExtras = intent.getExtras(); 
 if (bundleExtras != null) {                    
    for (String key : bundleExtras.keySet()) {                       
        if (!"launchArgs".equals(key)) {                            
          map.put(key, bundleExtras.get(key));                        
        }
   }
}
```
But of course it's your repo and you can do what you feel right.

**Comment by iamolegga** [comment] 2021-11-09 21:39
Hi all, can anyone check if this issue still persists in the latest version (2.0.1) or is it fixed with [this commit](https://github.com/iamolegga/react-native-launch-arguments/commit/5234a6830ee59327c59773b17737657193f0db7a)?

**Comment by iamolegga** [comment] 2022-01-25 14:51
Closing this issue as there are no new reports, looks like it's solved

**Closed by iamolegga** 2022-01-25 14:51 UTC
